describe('Verify eMag', () => {
    it('Verify title', () => {
        cy.visit('https://www.emag.ro/')
        cy.get('[data-id="190"]').eq(0).click()
        cy.get('[data-id="4078"]').click({ force: true })
        cy.get('.emg-aside-links > li > a').eq(0).click({ force: true })
        cy.get('[data-name="QLED"]').eq(0).click()
        cy.get('[data-name="Samsung"]').eq(0).click()
        cy.get('[data-option-id="3-5"]').click()
        cy.get('.col-sm-5 > .btn-primary').click()
        cy.get('.sort-control-btn-option').eq(1).click({ force: true })
        cy.get('[data-sort-id="price"]').eq(1).click({ force: true })
        cy.wait(3000);
        cy.get('.card-v2').eq(0).click()
        cy.get('.yeahIWantThisProduct').eq(1).click()
        cy.wait(3000)
        cy.get('.navbar-brand').click({ force: true })
        cy.get('[data-id="190"]').eq(0).click()
        cy.get('[data-id="4078"]').click({ force: true })
        cy.get('.emg-aside-links > li > a').eq(6).click({ force: true })
        cy.get('.sort-control-btn-option').eq(1).click({ force: true })
        cy.get('[data-sort-id="price"]').eq(0).click({ force: true })
        cy.wait(3000);
        cy.get('[data-name="Samsung"]').click()
        cy.get('[data-option-id="3-5"]').click()
        cy.wait(3000)
        cy.get('.card-v2').eq(0).click()
        cy.get('.yeahIWantThisProduct').eq(1).click()
        cy.contains('Vezi detalii cos').click()
        cy.get('.jewel').eq(1).should('have.text', '2')
    })
})